# Generated by Django 5.0 on 2025-07-23 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='date_created',
            new_name='created',
        ),
        migrations.AddField(
            model_name='expense',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FD', 'Food'), ('TRNSPT', 'Transport'), ('UTLTY', 'Utilities'), ('HSING', 'Housing'), ('HLTH', 'Health'), ('ENTTNMNT', 'Entertainment'), ('EDCTION', 'Education'), ('SHP', 'Shopping'), ('SVING', 'Savings'), ('DBT', 'Debt'), ('OTHR', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created'], name='expenses_ex_created_2763c8_idx'),
        ),
    ]
